id: e006e9c8f8da48478453dc7eb06ff22d
initial_creation_type: ocr
source_metadata:
  volumes:
    e553fbc1d2554bc8b4d20ac57cac0723:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: པདྨ་གཤིན་རྗེ་གཤེད་ཤེས་རབ་བདེ་བ་ཅན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
